mkdir "checkpoints"
wget -P "checkpoints" "https://www.ocf.berkeley.edu/~alexwan/mnist-arithmetic-checkpoints/baseline_10k.pth"
wget -P "checkpoints" "https://www.ocf.berkeley.edu/~alexwan/mnist-arithmetic-checkpoints/baseline_500.pth"
wget -P "checkpoints" "https://www.ocf.berkeley.edu/~alexwan/mnist-arithmetic-checkpoints/digitlbl_10k.pth"
wget -P "checkpoints" "https://www.ocf.berkeley.edu/~alexwan/mnist-arithmetic-checkpoints/digitlbl_500.pth"
wget -P "checkpoints" "https://www.ocf.berkeley.edu/~alexwan/mnist-arithmetic-checkpoints/explicit_10k.pth"
wget -P "checkpoints" "https://www.ocf.berkeley.edu/~alexwan/mnist-arithmetic-checkpoints/explicit_500.pth"
wget -P "checkpoints" "https://www.ocf.berkeley.edu/~alexwan/mnist-arithmetic-checkpoints/primaldual_10k.pth"
wget -P "checkpoints" "https://www.ocf.berkeley.edu/~alexwan/mnist-arithmetic-checkpoints/primaldual_500.pth"
wget -P "checkpoints" "https://www.ocf.berkeley.edu/~alexwan/mnist-arithmetic-checkpoints/samplingloss_10k.pth"
wget -P "checkpoints" "https://www.ocf.berkeley.edu/~alexwan/mnist-arithmetic-checkpoints/samplingloss_500.pth"
wget -P "checkpoints" "https://www.ocf.berkeley.edu/~alexwan/mnist-arithmetic-checkpoints/semanticloss_10k.pth"
wget -P "checkpoints" "https://www.ocf.berkeley.edu/~alexwan/mnist-arithmetic-checkpoints/semanticloss_500.pth"
