"""DFA primitives, builders, graph discovery, and tracing helpers."""

from importlib import import_module

_EXPORTS = {
    "ConstrainedGenerationResult": ".decoder",
    "ComposedRuntimeDFA": ".runtime",
    "ContextualDFA": ".conditioning",
    "ContextualTokenConstraintSpec": ".conditioning",
    "DFA": ".core",
    "DFATrace": ".visualization",
    "DFATraceStep": ".visualization",
    "DotSvgRenderResult": ".visualization",
    "GenerationBundle": ".encoder",
    "GenerationConstraintAnalysis": ".graph_discovery",
    "GenerationEncoder": ".encoder",
    "GenerationGraphContext": ".encoder",
    "ProductAutomatonTrace": ".visualization",
    "ProductReachabilityGraph": ".visualization",
    "ProductTraceStep": ".visualization",
    "State": ".core",
    "DecodeProgress": ".stop_policy",
    "StopPolicy": ".stop_policy",
    "Symbol": ".core",
    "RuntimeDFAOverlay": ".runtime",
    "TokenVocabulary": ".vocabulary",
    "accept_all_dfa": "._constraints",
    "after_token_allowed_dfa": "._constraints",
    "after_token_allowed_map_dfa": "._constraints",
    "first_token_allowed_dfa": "._constraints",
    "analyze_generation_constraints": ".graph_discovery",
    "bind_contextual_dfa": ".conditioning",
    "apply_all_constraints": ".generation_constraints",
    "apply_conditional_max_non_eos_constraint": ".generation_constraints",
    "apply_conditional_max_non_eos_constraints": ".generation_constraints",
    "apply_eos_closure_constraint": ".generation_constraints",
    "apply_forbidden_token_constraint": ".generation_constraints",
    "apply_forbidden_token_constraints": ".generation_constraints",
    "apply_max_non_eos_constraint": ".generation_constraints",
    "apply_required_token_constraint": ".generation_constraints",
    "apply_required_token_constraints": ".generation_constraints",
    "complement_dfa": ".core",
    "compose_runtime_dfa": ".runtime",
    "conditional_max_non_eos_dfa": "._constraints",
    "constrained_beam_search_decode": ".decoder",
    "constrained_greedy_decode": ".decoder",
    "constrained_label_beam_search_decode": ".decoder",
    "constrained_label_greedy_decode": ".decoder",
    "constrained_label_sample_decode": ".decoder",
    "constrained_sample_decode": ".decoder",
    "constraints_to_dfa_from_graph": ".graph_discovery",
    "create_generation_debug_app": ".visualization",
    "discover_generation_constraints": ".graph_discovery",
    "declare_contextual_token_constraint": ".conditioning",
    "discover_contextual_token_constraints": ".conditioning",
    "dfa_to_dot": ".visualization",
    "dot_to_svg": ".visualization",
    "empty_dfa": "._constraints",
    "eos_closure_dfa": "._constraints",
    "explain_dfa_rejection": ".visualization",
    "forbidden_token_dfa": "._constraints",
    "generation_bundle_from_graph": ".encoder",
    "mask_label_logits_for_dfa": ".decoder",
    "mask_logits_for_dfa": ".decoder",
    "max_non_eos_dfa": "._constraints",
    "mark_for_contextual_dfa": ".conditioning",
    "minimize_dfa": ".core",
    "normalize_lc": "._lc_normalize",
    "ordered_tokens_dfa": "._constraints",
    "product_dfa": ".core",
    "product_trace_to_dot": ".visualization",
    "reachable_product_graph": ".visualization",
    "render_dot_svg": ".visualization",
    "required_token_dfa": "._constraints",
    "run_generation_debug_server": ".visualization",
    "token_set_count_dfa": "._constraints",
    "pending_token_allowed_set_overlay": ".runtime",
    "trace_dfa": ".visualization",
    "trace_discrete_hmm": ".visualization",
    "trace_product_automaton": ".visualization",
    "token_class_sequence_overlay": ".runtime",
    "token_set_sequence_overlay": ".runtime",
    "union_dfa": ".core",
}

__all__ = sorted(_EXPORTS)


def __getattr__(name):
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name, __package__), name)
    globals()[name] = value
    return value
