"""Canonical lazy exports for generation learner automata and heads."""

from importlib import import_module

_EXPORTS = {
    'AllowedEmissionsSpec': '.hmm.graph.constraints',
    'AllowedTransitionsSpec': '.hmm.graph.constraints',
    'BaumWelchResult': '.hmm.discrete.discreteHMM',
    'CRFCompactLabelScorer': '.compact',
    'CompactLabelGenerationHead': '.common.base',
    'CompactLabelSequenceModel': '.common.base',
    'ConstraintApplicationReport': '.hmm.graph.constraints',
    'ConstraintDFAExportSpec': '.hmm.graph.constraints',
    'ConstraintHMMCompilation': '.hmm.graph.constraint_compiler',
    'ConstraintHMMState': '.hmm.graph.constraint_compiler',
    'DiscreteHMM': '.hmm.discrete.discreteHMM',
    'DomiKnowSAwareHMM': '.hmm.graph',
    'DynamicConstraintContext': '.hmm.graph.dynamic',
    'EmissionMaskSpec': '.hmm.graph.constraints',
    'EnergyCompactLabelGenerationHead': '.compact',
    'FactorizedStateSpace': '.hmm.graph.dynamic',
    'FiniteStateDynamicConstraint': '.hmm.graph.dynamic',
    'ForbiddenEmissionsSpec': '.hmm.graph.constraints',
    'ForbiddenTransitionsSpec': '.hmm.graph.constraints',
    'FrozenBackbonePromptEncoder': '.common.prompt_encoders',
    'GRUCompactLabelGenerationHead': '.compact',
    'GraphHMMGenerationHead': '.hmm.graph.graphAwareHMMLearner',
    'GraphSpectralAutomaton': '.wfa.graph',
    'GraphSpectralFitResult': '.wfa.graph',
    'GraphSpectralGenerationHead': '.wfa.graph_head',
    'HMMFactorGraphBundle': '.hmm.discrete.factors',
    'HMMFactorGraphContext': '.hmm.discrete.factors',
    'HMMFactorGraphEncoder': '.hmm.discrete.factors',
    'HMMFactorGraphHead': '.hmm.discrete.factors',
    'HMMFitResult': '.hmm.graph',
    'HMMForwardBackward': '.hmm.discrete.discreteHMM',
    'HMMGenerationHead': '.hmm.discrete.discreteHMMLearner',
    'HMMParameters': '.hmm.discrete.discreteHMM',
    'NeuralNGramCompactLabelGenerationHead': '.compact',
    'ProductDecoderState': '.wfa.hankel',
    'PromptConditionedSpectralWFAGenerationHead': '.wfa.prompt_conditioned_head',
    'PromptEmbeddingEncoder': '.common.prompt_encoders',
    'SpectralBasis': '.wfa.spectral_learning',
    'SpectralLearningResult': '.wfa.spectral_learning',
    'SpectralWFAFactorGraphBundle': '.wfa.factors',
    'SpectralWFAFactorGraphContext': '.wfa.factors',
    'SpectralWFAFactorGraphEncoder': '.wfa.factors',
    'SpectralWFAFactorGraphHead': '.wfa.factors',
    'SpectralWFAGenerationHead': '.wfa.head',
    'StatePredicateTransitionSpec': '.hmm.graph.constraints',
    'TransformerCompactLabelGenerationHead': '.compact',
    'TransitionMaskSpec': '.hmm.graph.constraints',
    'TransitionPotentialInput': '.common.utils',
    'ViterbiResult': '.hmm.graph',
    'WeightedFiniteAutomaton': '.wfa.hankel',
    'allowed_mass_loss': '.common.losses',
    'allowed_product_symbols': '.wfa.hankel',
    'apply_hmm_dp_consistency_constraints': '.hmm.discrete.factors',
    'apply_transition_energy': '.hmm.graph.dynamic',
    'apply_wfa_factor_consistency_constraints': '.wfa.factors',
    'baum_welch_train': '.hmm.discrete.discreteHMM',
    'build_spectral_basis': '.wfa.spectral_learning',
    'combine_masks': '.hmm.graph.constraints',
    'compare_hmm_dfa': '.hmm.discrete.discreteHMM',
    'compile_generation_constraints_to_hmm_support': '.hmm.graph.constraint_compiler',
    'constrained_hankel_matrix': '.wfa.hankel',
    'domiknows_hmm_from_generation_constraints': '.hmm.graph.constraint_compiler',
    'hankel_matrix': '.wfa.hankel',
    'hmm_dp_factor_consistency_loss': '.hmm.discrete.factors',
    'hmm_factor_sequence_nll': '.hmm.discrete.factors',
    'hmm_forward_backward_factors': '.hmm.discrete.factors',
    'hmm_sequence_nll': '.common.losses',
    'masked_empirical_initialization': '.wfa.graph',
    'normalize_matrix_rows': '.hmm.graph.constraints',
    'project_distribution': '.hmm.graph.constraints',
    'project_matrix': '.hmm.graph.constraints',
    'project_matrix_rows': '.hmm.graph.constraints',
    'projection_summary': '.wfa.hankel',
    'sequence_has_legal_path': '.wfa.graph',
    'spectral_learn_from_counts': '.wfa.spectral_learning',
    'spectral_learn_from_oracle': '.wfa.spectral_learning',
    'spectral_learn_from_samples': '.wfa.spectral_learning',
    'start_product_state': '.wfa.hankel',
    'step_product_state': '.wfa.hankel',
    'transition_energy_matrix': '.hmm.graph.dynamic',
    'validate_mask': '.hmm.graph.constraints',
    'wfa_factor_consistency_loss': '.wfa.factors',
    'wfa_factor_sequence_energy_loss': '.wfa.factors',
    'wfa_sequence_energy_loss': '.common.losses',
}

__all__ = sorted(_EXPORTS)


def __getattr__(name):
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name, __package__), name)
    globals()[name] = value
    return value
