"""Canonical lazy exports for generation learner automata and heads."""

from importlib import import_module

_EXPORTS = {
    'AllowedEmissionsSpec': '.hmm.constraints',
    'AllowedTransitionsSpec': '.hmm.constraints',
    'BaumWelchResult': '.hmm.core',
    'CRFCompactLabelScorer': '.compact',
    'CompactLabelGenerationHead': '.common.base',
    'CompactLabelSequenceModel': '.common.base',
    'ConstraintApplicationReport': '.hmm.constraints',
    'ConstraintDFAExportSpec': '.hmm.constraints',
    'ConstraintHMMCompilation': '.hmm.constraint_compiler',
    'ConstraintHMMState': '.hmm.constraint_compiler',
    'DFA': '.dfa.core',
    'DFATrace': '.dfa.visualization',
    'DFATraceStep': '.dfa.visualization',
    'DiscreteHMM': '.hmm.core',
    'DomiKnowSAwareHMM': '.hmm.graph',
    'DomiKnowSGraphAdapter': '.hmm.graph_adapter',
    'DynamicConstraintContext': '.hmm.dynamic',
    'EmissionMaskSpec': '.hmm.constraints',
    'EnergyCompactLabelGenerationHead': '.compact',
    'FactorizedStateSpace': '.hmm.dynamic',
    'FiniteStateDynamicConstraint': '.hmm.dynamic',
    'ForbiddenEmissionsSpec': '.hmm.constraints',
    'ForbiddenTransitionsSpec': '.hmm.constraints',
    'FrozenBackbonePromptEncoder': '.common.prompt_encoders',
    'GRUCompactLabelGenerationHead': '.compact',
    'GraphHMMGenerationHead': '.hmm.graph_head',
    'GraphSpectralAutomaton': '.wfa.graph',
    'GraphSpectralFitResult': '.wfa.graph',
    'GraphSpectralGenerationHead': '.wfa.graph_head',
    'HMMFactorGraphBundle': '.hmm.factors',
    'HMMFactorGraphContext': '.hmm.factors',
    'HMMFactorGraphEncoder': '.hmm.factors',
    'HMMFactorGraphHead': '.hmm.factors',
    'HMMFitResult': '.hmm.graph',
    'HMMForwardBackward': '.hmm.core',
    'HMMGenerationHead': '.hmm.head',
    'HMMParameters': '.hmm.core',
    'NeuralNGramCompactLabelGenerationHead': '.compact',
    'ProductAutomatonTrace': '.dfa.visualization',
    'ProductDecoderState': '.wfa.hankel',
    'ProductReachabilityGraph': '.dfa.visualization',
    'ProductTraceStep': '.dfa.visualization',
    'PromptConditionedHMMGenerationHead': '.hmm.prompt_conditioned_head',
    'PromptConditionedSpectralWFAGenerationHead': '.wfa.prompt_conditioned_head',
    'PromptEmbeddingEncoder': '.common.prompt_encoders',
    'SpectralBasis': '.wfa.spectral_learning',
    'SpectralLearningResult': '.wfa.spectral_learning',
    'SpectralWFAFactorGraphBundle': '.wfa.factors',
    'SpectralWFAFactorGraphContext': '.wfa.factors',
    'SpectralWFAFactorGraphEncoder': '.wfa.factors',
    'SpectralWFAFactorGraphHead': '.wfa.factors',
    'SpectralWFAGenerationHead': '.wfa.head',
    'State': '.dfa.core',
    'StatePredicateTransitionSpec': '.hmm.constraints',
    'Symbol': '.dfa.core',
    'TransformerCompactLabelGenerationHead': '.compact',
    'TransitionMaskSpec': '.hmm.constraints',
    'TransitionPotentialInput': '.common.utils',
    'ViterbiResult': '.hmm.graph',
    'WeightedFiniteAutomaton': '.wfa.hankel',
    'all_sequences': '.hmm.core',
    'allowed_mass_loss': '.common.losses',
    'allowed_product_symbols': '.wfa.hankel',
    'apply_hmm_dp_consistency_constraints': '.hmm.factors',
    'apply_transition_energy': '.hmm.dynamic',
    'apply_wfa_factor_consistency_constraints': '.wfa.factors',
    'baum_welch_train': '.hmm.core',
    'build_spectral_basis': '.wfa.spectral_learning',
    'combine_masks': '.hmm.constraints',
    'compare_hmm_dfa': '.hmm.core',
    'compile_generation_constraints_to_hmm_support': '.hmm.constraint_compiler',
    'complement_dfa': '.dfa.core',
    'constrained_hankel_matrix': '.wfa.hankel',
    'dfa_to_dot': '.dfa.visualization',
    'domiknows_hmm_from_generation_constraints': '.hmm.constraint_compiler',
    'explain_dfa_rejection': '.dfa.visualization',
    'hankel_matrix': '.wfa.hankel',
    'hmm_dp_factor_consistency_loss': '.hmm.factors',
    'hmm_factor_sequence_nll': '.hmm.factors',
    'hmm_forward_backward_factors': '.hmm.factors',
    'hmm_sequence_nll': '.common.losses',
    'masked_empirical_initialization': '.wfa.graph',
    'normalize_matrix_rows': '.hmm.constraints',
    'product_dfa': '.dfa.core',
    'product_trace_to_dot': '.dfa.visualization',
    'project_distribution': '.hmm.constraints',
    'project_matrix': '.hmm.constraints',
    'project_matrix_rows': '.hmm.constraints',
    'projection_summary': '.wfa.hankel',
    'reachable_product_graph': '.dfa.visualization',
    'sequence_has_legal_path': '.wfa.graph',
    'spectral_learn_from_counts': '.wfa.spectral_learning',
    'spectral_learn_from_oracle': '.wfa.spectral_learning',
    'spectral_learn_from_samples': '.wfa.spectral_learning',
    'start_product_state': '.wfa.hankel',
    'step_product_state': '.wfa.hankel',
    'trace_dfa': '.dfa.visualization',
    'trace_discrete_hmm': '.dfa.visualization',
    'trace_product_automaton': '.dfa.visualization',
    'transition_energy_matrix': '.hmm.dynamic',
    'union_dfa': '.dfa.core',
    'validate_mask': '.hmm.constraints',
    'wfa_factor_consistency_loss': '.wfa.factors',
    'wfa_factor_sequence_energy_loss': '.wfa.factors',
    'wfa_sequence_energy_loss': '.common.losses',
}

__all__ = sorted(_EXPORTS)


def __getattr__(name):
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name, __package__), name)
    globals()[name] = value
    return value
