name: CI - Continuous Integration for develop-CLEVER-relations  Branch
on:
  push: { branches: [develop-CLEVER-relations] }
  pull_request: { branches: [develop-CLEVER-relations] }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out the repository branch develop-CLEVER-relations under $GITHUB_WORKSPACE, so the workflow job can access it
      - uses: actions/checkout@v4
        with:
          ref: "develop-CLEVER-relations"

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: "3.12" }

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Resolve & install
        run: |
         uv sync --extra cpu --extra dev 

      - name: Run regression tests
        run: |
          # List of specific test subfolders to run from test_regr folder
          # Add subfolder names to this array as needed
          TEST_LIST=(
            'example/conll04'
            'example/graph_coloring'
            'example/edges'
            'example/equality'
            'example/orbs'
          )
          
          if [ ${#TEST_LIST[@]} -eq 0 ]; then
            echo "No test subfolders specified in TEST_LIST. Skipping test execution."
            exit 0
          fi
          
          # Run tests from specified subfolders in test_regr (relative to workspace)
          for subfolder in "${TEST_LIST[@]}"; do
            echo "Running tests in test_regr/$subfolder"
            if [ -d "test_regr/$subfolder" ]; then
              uv run pytest -q "test_regr/$subfolder"
            else
              echo "Warning: Directory test_regr/$subfolder not found, skipping..."
            fi
          done