name: CI - Continuous Integration for develop-CLEVER-relations  Branch
on:
  push: { branches: [develop-CLEVER-relations] }
  pull_request: { branches: [develop-CLEVER-relations] }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out the repository branch develop-CLEVER-relations under $GITHUB_WORKSPACE, so the workflow job can access it
      - uses: actions/checkout@v4
        with:
          ref: "develop-CLEVER-relations"

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: "3.13" }

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Resolve & install
        run: |
         uv sync --extra cpu --extra dev 

      - name: Run regression tests
        run: |
          # List of specific test subfolders to run from test_regr/examples
          # Add subfolder names to this array as needed
          TEST_LIST=(
            'examples/conll04'
            'examples/edges'
            'examples/equality'
            'examples/orbs'
            'examples/graph_coloring'
          )
          
          if [ ${#TEST_LIST[@]} -eq 0 ]; then
            echo "No test subfolders specified in TEST_LIST. Skipping test execution."
            exit 0
          fi
          
          TEST_BASE_DIR="test_regr"
          echo "Using test base directory: $TEST_BASE_DIR"
          
          # Show available test directories for debugging
          echo "Available test directories in $TEST_BASE_DIR:"
          find "$TEST_BASE_DIR" -type d -name "*" | sort
          
          # Run tests from specified subfolders
          for subfolder in "${TEST_LIST[@]}"; do
            test_path="$TEST_BASE_DIR/$subfolder"
            echo "Running tests in $test_path"
            if [ -d "$test_path" ]; then
              uv run pytest -q "$test_path"
            else
              echo "Warning: Directory $test_path not found, skipping..."
            fi
          done