name: Generate Requirements Files

on:
  push:
    branches: [main]
    paths-ignore:
      - 'requirements*.txt'

jobs:
  generate-requirements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Generate requirements.txt (CPU)
        run: |
          uv export --extra cpu --no-hashes --no-dev -o requirements.txt

      - name: Generate requirements-dev.txt (CPU)
        run: |
          uv export --extra cpu --extra dev --no-hashes -o requirements-dev.txt

      - name: Generate requirements-cu128.txt (CUDA 12.8)
        run: |
          uv export --extra cu128 --no-hashes --no-dev -o requirements-cu128.txt

      - name: Generate requirements-cu128-dev.txt (CUDA 12.8)
        run: |
          uv export --extra cu128 --extra dev --no-hashes -o requirements-cu128-dev.txt

      - name: Generate requirements-cu126.txt (CUDA 12.6)
        run: |
          uv export --extra cu126 --no-hashes --no-dev -o requirements-cu126.txt

      - name: Generate requirements-cu126-dev.txt (CUDA 12.6)
        run: |
          uv export --extra cu126 --extra dev --no-hashes -o requirements-cu126-dev.txt

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add requirements*.txt
          git diff --staged --quiet || git commit -m "chore: update requirements files [skip ci]"
          git push